#!/usr/bin/env python3.5

import socketserver
import socket
import logging
import argparse

from sgx.util import check_msg
from sgx.socket_util import send_msg, receive_msg
from sgx.untrusted.attestation import get_extended_epid_group_id
from sgx.untrusted.attestation import initialize_quoting_enclave
from sgx.untrusted.attestation import get_quote_size
from sgx.untrusted.attestation import get_quote


manager = None


class RequestHandler(socketserver.StreamRequestHandler):

    _request_num = 0

    def __init__(self, *args, **kwargs):
        self._request_num += 1
        self.id = self._request_num
        self.logger = logging.getLogger("Request#%s" % self.id)
        super(RequestHandler, self).__init__(*args, **kwargs)

    def handle(self):
        client_socket = self.request

        msg = receive_msg(client_socket)
        check_msg(msg, dict)

        request = msg["request"]
        self.logger.info("Got request %r", request)

        if request == "GET extended_epid_gid":
            extended_epid_gid = get_extended_epid_group_id()
            self.send_extended_epid_gid(client_socket, extended_epid_gid)

        if request == "INIT QE":
            qe_target_info, epid_gid = initialize_quoting_enclave()
            self.send_qe_init_response(client_socket, qe_target_info, epid_gid)

        if request == "GET QUOTE":
            report = bytes.fromhex(msg["report"])
            quote_type = msg["quote_type"]
            spid = bytes.fromhex(msg["spid"])
            nonce = bytes.fromhex(msg["nonce"])
            revocation_list = bytes.fromhex(msg["revocation_list"])

            self.logger.warning("revocation list: %r", revocation_list)

            quote_size = get_quote_size(revocation_list)
            quote, qe_report = get_quote(report, quote_type, spid, nonce, revocation_list, quote_size)

            self.send_quote(client_socket, quote, qe_report)

    def send_extended_epid_gid(self, client_socket: socket.socket, extended_epid_gid):
        msg = {"extended_epid_gid": extended_epid_gid}
        self.logger.info("Sending extended EPID group ID (message size: %r)", len(msg))
        send_msg(client_socket, msg)
        self.logger.info("Extended EPID group ID sent")

    def send_qe_init_response(self, client_socket: socket.socket, qe_target_info, epid_gid):
        msg = {"qe_target_info": qe_target_info.hex(), "epid_gid": epid_gid.hex()}
        self.logger.info("Sending quoting enclave init response (message size: %r)", len(msg))
        send_msg(client_socket, msg)
        self.logger.info("Quoting enclave init response sent")

    def receive_report(self, client_socket: socket.socket):
        self.logger.info("Waiting for report")
        msg = receive_msg(client_socket)
        check_msg(msg, dict, 1)
        return bytes.fromhex(msg["report"])

    def send_quote(self, client_socket: socket.socket, quote, qe_report):
        msg = {"quote": quote.hex(), "qe_report": qe_report.hex()}
        self.logger.info("Sending quote")
        send_msg(client_socket, msg)
        self.logger.info("Quote sent")


class Manager(object):
    def __init__(self, interface, port):
        self.interface = interface
        self.port = port
        self.server = socketserver.TCPServer((interface, port), RequestHandler)
        self.logger = logging.getLogger("Manager")

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.logger.info("Stopping server")
        self.server.server_close()

    def run(self):
        self.logger.info("Listening for attestation requests on %s:%s", self.interface, self.port)
        self.server.serve_forever()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--interface", "-i", default="127.0.0.1")
    parser.add_argument("--port", "-p", type=int, default=9876)
    parser.add_argument("--verbose", "-v", action="store_true")
    return parser.parse_args()


def init(args):
    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)


def main():
    args = parse_args()
    init(args)

    global manager
    with Manager(args.interface, args.port) as manager:
        manager.run()


if __name__ == "__main__":
    main()
